name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Update to a supported Node.js version (16 or 18)

      - name: Install dependencies
        run: npm ci # Ensure clean install

      - name: Build the project
        run: npm run build # Build the project using Vite

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MUANOMASIAGWALA_D678D }}
          channelId: live
          projectId: muanomasiagwala-d678d
