name: Deploy to Firebase Hosting on PR

on:
  pull_request:
    branches:
      - main # Trigger only for PRs to the 'main' branch or change it to your target branch

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Set the Node.js version as per your project requirement

      - name: Install dependencies
        run: npm ci # Using npm ci for consistent installs with package-lock.json

      - name: Build the project
        run: npm run build # Make sure your 'build' script is defined in your package.json

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MUANOMASIAGWALA_D678D }}
          projectId: muanomasiagwala-d678d
        env:
          FIREBASE_CLI_LOGIN: ${{ secrets.FIREBASE_CLI_LOGIN }} # If you're using Firebase CLI login, set it here
